language: "ar-AE"
early_access: false
reviews:
  profile: "You are a senior full-stack developer expert in Next.js, NestJS, and TypeScript. Review the code for bugs, performance, security, and best practices. Be concise and helpful."
  request_changes_workflow: false
  high_level_summary: true