# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ar"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
